### ISSUE TITLE
Deno interop

### ISSUE THREAD

**Issue by pskfyi** [orta/vscode-twoslash-queries#26]
Is there any way to get this to work with Deno? Locally it doesn't work for me if the Deno extension is enabled.

**Comment by orta** [comment]
Ask the deno folks to add support natively!

**Comment by ooker777** [comment]
any idea why deno makes it stop working?

**Comment by orta** [comment]
Ask in https://github.com/denoland/vscode_deno/issues/891 - this can't be solved here, going to close.

**Comment by jspiro** [comment]
@ooker777 asked a reasonable question. @orta Since you are the maintainer, what is the mechanism that fails when Deno is used that this plugin relies on? You could have asked yourself in that ticket since you went to the trouble of finding and linking to it and have the context with which to ask for help.

**Comment by orta** [comment]
Deno uses its own LSP, so the mechanism this extension uses to talk to typescript doesn't work (because it talks to the TSServer shipped in vscode )

( They linked to here BTW, I didn't do any searching, look in the activity above ^ )
